services:
  postgres:
    image: postgres:16
    container_name: postgres_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: ReserveDB
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network
    restart: unless-stopped

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - app-network
    restart: unless-stopped

  reservservice:
    image: ${DOCKER_REGISTRY-}reservservice
    build:
      context: .
      dockerfile: Services/Reserve/Reserve.WebApi/Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_HTTP_PORTS: 8080
      DATABASE_URL: postgresql://postgres:12345@postgres:5432/ReserveDB
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: ReserveDB
      DB_USER: postgres
      DB_PASSWORD: 12345
    ports:
      - "8000:8080"
    depends_on:
      - postgres
    networks:
      - app-network
    restart: unless-stopped

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge
