<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.9.0" />
    <PackageReference Include="Polly.Extensions.Http" Version="3.0.0" />
    <PackageReference Include="Microsoft.Extensions.Http.Polly" Version="8.0.11" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="9.0.10" />
    <PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="8.2.1" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Relational" Version="9.0.10" />
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="9.0.4" />
    <PackageReference Include="MassTransit" Version="8.2.5" />
    <PackageReference Include="MassTransit.RabbitMQ" Version="8.2.5" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Admin.Application\Admin.Application.csproj" />
    <ProjectReference Include="..\Admin.Infrastructure\Admin.Infrastructure.csproj" />
    <ProjectReference Include="..\..\Hotels\Hotels.Infrastructure\Hotels.Infrastructure.csproj" />
    <ProjectReference Include="..\..\Shared\Shared.Contracts\Shared.Contracts.csproj" />
  </ItemGroup>

</Project>
